/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyFSMStandaloneSetup extends MyFSMStandaloneSetupGenerated {

	def static void doSetup() {
		new MyFSMStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
