/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyFSMRuntimeModule extends AbstractMyFSMRuntimeModule {
}
