/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.ui;

import fr.ut2j.m1ice.fsm.texteditor.ui.AbstractMyFSMUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyFSMUiModule extends AbstractMyFSMUiModule {
  public MyFSMUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
