/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.ui.tests;

import com.google.inject.Injector;
import fr.ut2j.m1ice.fsm.texteditor.ui.internal.TexteditorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyFSMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TexteditorActivator.getInstance().getInjector("fr.ut2j.m1ice.fsm.texteditor.MyFSM");
	}

}
