/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.ut2j.m1ice.fsm.texteditor.MyFSMRuntimeModule;
import fr.ut2j.m1ice.fsm.texteditor.MyFSMStandaloneSetup;
import fr.ut2j.m1ice.fsm.texteditor.ide.MyFSMIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyFSMIdeSetup extends MyFSMStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyFSMRuntimeModule _myFSMRuntimeModule = new MyFSMRuntimeModule();
    MyFSMIdeModule _myFSMIdeModule = new MyFSMIdeModule();
    return Guice.createInjector(Modules2.mixin(_myFSMRuntimeModule, _myFSMIdeModule));
  }
}
