/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.ide;

import fr.ut2j.m1ice.fsm.texteditor.ide.AbstractMyFSMIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyFSMIdeModule extends AbstractMyFSMIdeModule {
}
