/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.ui.contentassist;

import fr.ut2j.m1ice.fsm.texteditor.ui.contentassist.AbstractMyFSMProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyFSMProposalProvider extends AbstractMyFSMProposalProvider {
}
