/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.validation;

import fr.ut2j.m1ice.fsm.texteditor.validation.AbstractMyFSMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyFSMValidator extends AbstractMyFSMValidator {
}
