/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class MyFSMQuickfixProvider extends DefaultQuickfixProvider {
}
