/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor;

import fr.ut2j.m1ice.fsm.texteditor.MyFSMStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyFSMStandaloneSetup extends MyFSMStandaloneSetupGenerated {
  public static void doSetup() {
    new MyFSMStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
