/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.texteditor.parser.antlr;

import com.google.inject.Inject;
import fr.ut2j.m1ice.fsm.texteditor.parser.antlr.internal.InternalMyFSMParser;
import fr.ut2j.m1ice.fsm.texteditor.services.MyFSMGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyFSMParser extends AbstractAntlrParser {

	@Inject
	private MyFSMGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyFSMParser createParser(XtextTokenStream stream) {
		return new InternalMyFSMParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FSM";
	}

	public MyFSMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyFSMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
